'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AnthroAddIn.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property BrowserSlotPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BrowserSlotPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Component() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Component", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property DimensionPrecision() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("DimensionPrecision", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Draw() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Draw", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property DrawSlot() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("DrawSlot", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property DWF_Viewer() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("DWF_Viewer", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property DXFIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("DXFIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property edit() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property electricity() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("electricity", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property FileFolder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FileFolder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property fix() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("fix", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property iProperty() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("iProperty", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property PCB() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PCB", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property printer() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property SelectCenters() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectCenters", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SelectCentersWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectCentersWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SelectPointDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectPointDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SelectPointUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectPointUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SlotFeature() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SlotFeature", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property TO_220() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("TO_220", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property TopArea() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("TopArea", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
